Rework setup grammar script to better handle more targets.
crate/cratedb-sqlparse pull request #4
Opened 2024-04-15 18:32 UTC by surister

## Summary of the changes / Why this is an improvement

setup_grammar (for the lack of better name) is the script that handles downloading the grammar, compiling it, fixing it.. etc

It needed some love to better reflect the many-targets nature of the repo.

## Checklist

 - [ ] Link to issue this PR refers to (if applicable): 
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

2024-04-15 19:16 UTC, amotl requested changes

2024-04-15 19:16 UTC, amotl commented on setup_grammar.py
> +            'url': 'https://raw.githubusercontent.com/crate/crate/{version}/libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4',
Makes a shorter URL, but adds a redirect at runtime. It's probably a matter of taste.

```suggestion
            'url': 'https://github.com/crate/crate/{version}/libs/sql-parser/src/raw/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4',
```

2024-04-15 19:16 UTC, amotl commented on setup_grammar.py
> +            f.write(text)
Should not write into the path of `__file__` on a later occasion, right? Did you mean to say `Path.cwd()` instead?

2024-04-15 19:16 UTC, amotl commented on setup_grammar.py
> +        ], shell=True)
Why does that use a shell, with `echo`, to write a string into a file? Most probably, it has a valid reason, and I am missing something?

2024-04-15 19:16 UTC, amotl commented on setup_grammar.py
> +        ], shell=True)
Dito.

2024-04-15 21:20 UTC, surister commented on setup_grammar.py
> +        ], shell=True)
It allows the whole command to be a single string https://docs.python.org/3/library/subprocess.html#frequently-used-arguments instead of a list or arguments

2024-04-15 21:28 UTC, surister commented on setup_grammar.py
> +            f.write(text)
No I didn't mean to, it's an idiom that I drag from where I wrote  django applications, `BASE_DIR = pathlib.Path(__file__).parent` is a default setting on `settings.py` but nonetheless It definitely sounds better, thanks! didn't remember that `pathlib.Path(__file__).parent == pathlib.Path.cwd()`.

2024-04-15 21:42 UTC, amotl commented on setup_grammar.py
> +            f.write(text)
> Didn't know that `pathlib.Path(__file__).parent == pathlib.Path.cwd()`.

Well, it's not always equal. On the left, it's the parent folder of the Python file (might also be within an egg), and on the right, it's the actual current working directory, also printable using the `pwd` command.

2024-04-15 21:45 UTC, amotl commented on setup_grammar.py
> +        ], shell=True)
Thanks. I did not mean to ask about the specific `shell` argument of `subprocess`, but merely why that code uses a [shellout](https://linux.die.net/man/3/shellout) at all, to write text into a file?

2024-04-15 21:48 UTC, surister commented on setup_grammar.py
> +            'url': 'https://raw.githubusercontent.com/crate/crate/{version}/libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4',
`https://github.com/crate/crate/5.6.4/libs/sql-parser/src/raw/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4` doesn't seem to be valid

2024-04-15 21:53 UTC, amotl commented on setup_grammar.py
> +            'url': 'https://raw.githubusercontent.com/crate/crate/{version}/libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4',
That one is a valid link. I've conveyed the `raw` at the wrong place. Apologies.

https://github.com/crate/crate/raw/5.6.4/libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4

2024-04-15 21:58 UTC, surister commented on setup_grammar.py
> +            'url': 'https://raw.githubusercontent.com/crate/crate/{version}/libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4',
gotcha

2024-04-16 09:47 UTC, surister commented on setup_grammar.py
> +        ], shell=True)
Seemed to me the quickest and easiest way to add the used CrateDB grammar version into the targets

2024-04-16 10:53 UTC, amotl commented on setup_grammar.py
> +        ], shell=True)
Why not use pure Python, also to be platform agnostic from the start and without further ado, not relying on external shell implementations?
```python
with open(target_path / "__init__.py", "w+") as f:
    f.write(f"__cratedb_version__ = {version}\n")
```

2024-04-16 10:59 UTC, surister commented on setup_grammar.py
> +        ], shell=True)
Fair enough thanks

2024-04-16 11:16 UTC, merged